## URLs:
GitHub: [https://github.com/gabrielloye/LSTM_Sentiment-Analysis/blob/master/LSTM_starter.ipynb](https://github.com/gabrielloye/LSTM_Sentiment-Analysis/blob/master/LSTM_starter.ipynb)

Article: [https://blog.floydhub.com/long-short-term-memory-from-zero-to-hero-with-pytorch/](https://blog.floydhub.com/long-short-term-memory-from-zero-to-hero-with-pytorch/)

In [1]:
import torch
import torch.nn as nn

In [2]:
input_dim = 5
hidden_dim = 10
n_layers = 1  # Output shapes will * n_layers if > 1. 

lstm_layer = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True)

In [3]:
batch_size = 1
seq_len = 1

inp = torch.randn(batch_size, seq_len, input_dim)
hidden_state = torch.randn(n_layers, batch_size, hidden_dim)
cell_state = torch.randn(n_layers, batch_size, hidden_dim)
hidden = (hidden_state, cell_state)
print("Input shape: {}".format(inp.shape))
print("Hidden shape: ({}, {})".format(hidden[0].shape, hidden[1].shape))

Input shape: torch.Size([1, 1, 5])
Hidden shape: (torch.Size([1, 1, 10]), torch.Size([1, 1, 10]))


In [4]:
out, (hidden_n, cell_n) = lstm_layer(inp, hidden)
print("Output shape: ", out.shape, "\n")
print("Hidden:\n", hidden_n, "\nShape: ", hidden_n.shape, "\n")
print("Cell:\n", cell_n, "\nShape: ", cell_n.shape, "\n")

Output shape:  torch.Size([1, 1, 10]) 

Hidden:
 tensor([[[ 0.0955, -0.2894, -0.0251,  0.0543,  0.3613, -0.5282,  0.0031,
          -0.1859, -0.1644, -0.1628]]], grad_fn=<StackBackward>) 
Shape:  torch.Size([1, 1, 10]) 

Cell:
 tensor([[[ 0.2759, -0.3867, -0.0431,  0.1646,  1.0879, -1.3404,  0.0095,
          -0.4426, -0.2365, -0.3460]]], grad_fn=<StackBackward>) 
Shape:  torch.Size([1, 1, 10]) 



In [7]:
seq_len = 3  # Longer sequence length, can use same LSTM.
inp = torch.randn(batch_size, seq_len, input_dim)
out, (hidden_n, cell_n) = lstm_layer(inp, (hidden_n, cell_n))
print("Output shape: ", out.shape, "\n")
print("Output:\n", out)

Output shape:  torch.Size([1, 3, 10]) 

Output:
 tensor([[[-0.1305, -0.0601, -0.0701,  0.1518,  0.1705, -0.1332,  0.0758,
          -0.0055, -0.3079,  0.2000],
         [-0.0990, -0.0169, -0.0804,  0.2670,  0.1299, -0.0750,  0.0852,
           0.1195,  0.0369,  0.1179],
         [-0.2027,  0.0528,  0.0823,  0.0515,  0.0428, -0.0816,  0.1754,
           0.0373, -0.1753,  0.2618]]], grad_fn=<TransposeBackward0>)


In [8]:
# Obtaining the last output in the sequence
out = out.squeeze()[-1, :]  # Note -1 is used to take last, this is not .view()! 
print("Output shape: ", out.shape, "\n")
print("Output:\n", out)

Output shape:  torch.Size([10]) 

Output:
 tensor([-0.0990, -0.0169, -0.0804,  0.2670,  0.1299, -0.0750,  0.0852,  0.1195,
         0.0369,  0.1179], grad_fn=<SliceBackward>)
