# Deep Learning with PyTorch: A 60 Minute Blitz > What is PyTorch?

## Getting Started

### Tensors 

In [1]:
import torch

#### Construct a 5x3 matrix, uninitialized.

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [7]:
x = torch.empty(5, 3)
print(x)
display(x)

# Uninitialised - gibberish values!

tensor([[-1.0169e-01,  3.0718e-41, -1.0168e-01],
        [ 3.0718e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.0177e-01],
        [ 3.0718e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


tensor([[-1.0169e-01,  3.0718e-41, -1.0168e-01],
        [ 3.0718e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.0177e-01],
        [ 3.0718e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

#### Construct a randomly initialized matrix.

In [8]:
x = torch.rand(5, 3)  # Note: no need for tuple inside brackets.
x

tensor([[0.1519, 0.4708, 0.9649],
        [0.9611, 0.9893, 0.7501],
        [0.5662, 0.8297, 0.1203],
        [0.7836, 0.4188, 0.7554],
        [0.3402, 0.4251, 0.6797]])

#### Construct a matrix filled zeros and of dtype long.

In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
display(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

torch.int64


#### Construct a tensor directly from data.

In [12]:
x = torch.tensor([5.5, 3])  # Note the tensor() method.
x

tensor([5.5000, 3.0000])

#### Create a tensor based on an existing tensor. 

These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.

`_like` siffix.

In [13]:
tensor_template_ones = x.new_ones(5, 3, dtype=torch.double)  # new_* methods take in sizes
display(tensor_template_ones)

tensor_from_template = torch.randn_like(tensor_template_ones, dtype=torch.float)  # From template (will be same shape), override dtype.
display(tensor_from_template)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

tensor([[ 1.0448, -0.2375,  1.7379],
        [ 1.0179, -1.7118,  1.1146],
        [ 0.8465,  1.1806, -0.5590],
        [ 1.2258, -0.5153, -0.5436],
        [ 1.2751,  1.2362, -0.3090]])

In [15]:
x = x.new_ones(3, 2, dtype=torch.double)  # Aka torch.float64
y = x.new_zeros(2, 3, dtype=torch.float)
display(x, y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### Size

In [17]:
display(x.size())
display(y.size())

torch.Size([3, 2])

torch.Size([2, 3])

In [19]:
display(x.shape)  # .shape redirects to .size()

torch.Size([3, 2])

Note: torch.Size is in fact a tuple, so it supports all tuple operations.

In [20]:
print(x.size()[1])
print(x.shape[0])

2
3


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

#### Addition: syntax 1

In [21]:
x = torch.rand(5, 3)
y = torch.randn(5, 3)
display(x, y, x + y)

tensor([[0.3269, 0.0461, 0.9323],
        [0.0728, 0.6950, 0.0481],
        [0.4402, 0.9372, 0.3875],
        [0.2059, 0.6262, 0.1729],
        [0.9092, 0.7811, 0.7888]])

tensor([[ 0.0922, -2.0253,  1.6453],
        [ 0.1423, -1.0763, -0.9724],
        [-0.9655,  0.0033, -1.1647],
        [ 1.3849,  0.8166,  1.8091],
        [-2.3842, -1.7635,  0.2394]])

tensor([[ 0.4191, -1.9792,  2.5776],
        [ 0.2151, -0.3813, -0.9243],
        [-0.5253,  0.9405, -0.7772],
        [ 1.5908,  1.4428,  1.9820],
        [-1.4750, -0.9824,  1.0282]])

#### Addition: syntax 2

In [22]:
x.add(y)  # As a method

tensor([[ 0.4191, -1.9792,  2.5776],
        [ 0.2151, -0.3813, -0.9243],
        [-0.5253,  0.9405, -0.7772],
        [ 1.5908,  1.4428,  1.9820],
        [-1.4750, -0.9824,  1.0282]])

#### Addition: providing an output tensor as argument

In [24]:
result = torch.empty(5, 3)
display(result)
torch.add(x, y, out=result)  # As a "static" method on torch, with `out` parameter.
display(result)

tensor([[-1.0635e-01,  3.0718e-41, -1.0634e-01],
        [ 3.0718e-41,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-1.0163e-01,  3.0718e-41,  9.1084e-44]])

tensor([[ 0.4191, -1.9792,  2.5776],
        [ 0.2151, -0.3813, -0.9243],
        [-0.5253,  0.9405, -0.7772],
        [ 1.5908,  1.4428,  1.9820],
        [-1.4750, -0.9824,  1.0282]])

In [25]:
result2 = torch.add(x, y)
result2

tensor([[ 0.4191, -1.9792,  2.5776],
        [ 0.2151, -0.3813, -0.9243],
        [-0.5253,  0.9405, -0.7772],
        [ 1.5908,  1.4428,  1.9820],
        [-1.4750, -0.9824,  1.0282]])

#### Addition: in-place 

In [26]:
y.add_(x)  # IN-PLACE (note the underscore): `<tensor>.<operation_>`
display(y)

tensor([[ 0.4191, -1.9792,  2.5776],
        [ 0.2151, -0.3813, -0.9243],
        [-0.5253,  0.9405, -0.7772],
        [ 1.5908,  1.4428,  1.9820],
        [-1.4750, -0.9824,  1.0282]])

**Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.**

#### NumPy-like indexing

In [28]:
display(x[:, 1])
type(x[:, 1])

tensor([0.0461, 0.6950, 0.9372, 0.6262, 0.7811])

torch.Tensor

#### Resizing: If you want to resize/reshape tensor, you can use `torch.view`

In [31]:
x = torch.randn(4, 4)

# The method is .view(), not .resize(). Returns a tensor though, not some other type.
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions

display(x, y, z)
print("---")
display(type(x), type(y), type(z))
print("---")
display(x.size(), y.size(), z.size())

tensor([[ 0.2108,  0.0656, -0.8400, -0.3677],
        [-1.1391,  0.4992,  0.2137, -0.4796],
        [ 0.1626,  1.4863,  1.6208, -1.4784],
        [-1.1531,  0.5094,  1.0301, -2.1767]])

tensor([ 0.2108,  0.0656, -0.8400, -0.3677, -1.1391,  0.4992,  0.2137, -0.4796,
         0.1626,  1.4863,  1.6208, -1.4784, -1.1531,  0.5094,  1.0301, -2.1767])

tensor([[ 0.2108,  0.0656, -0.8400, -0.3677, -1.1391,  0.4992,  0.2137, -0.4796],
        [ 0.1626,  1.4863,  1.6208, -1.4784, -1.1531,  0.5094,  1.0301, -2.1767]])

---


torch.Tensor

torch.Tensor

torch.Tensor

---


torch.Size([4, 4])

torch.Size([16])

torch.Size([2, 8])

#### If you have a one element tensor, use `.item()` to get the value as a Python number

In [32]:
x = torch.randn(1)
display(x)
display(x.item())  # Extract the value as a Python number.

tensor([0.1358])

0.13583825528621674

#### Reference: [here](https://pytorch.org/docs/torch)

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [35]:
a = torch.ones(5)
display(type(a))
a

torch.Tensor

tensor([1., 1., 1., 1., 1.])

In [37]:
# .numpy() method to convert.
b = a.numpy()
display(type(b))
b

numpy.ndarray

array([1., 1., 1., 1., 1.], dtype=float32)

In [39]:
# Note the shared memory! Both change.
a.add_(100)
display(a, b)

tensor([101., 101., 101., 101., 101.])

array([101., 101., 101., 101., 101.], dtype=float32)

### Converting NumPy Array to Torch Tensor 

In [40]:
import numpy as np

In [42]:
# torch.from_numpy() method to convert.
a = np.ones((2, 4))
b = torch.from_numpy(a)
display(a, b)

# Note shared memory.
np.add(a, 200, out=a)
display(a, b)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

array([[201., 201., 201., 201.],
       [201., 201., 201., 201.]])

tensor([[201., 201., 201., 201.],
        [201., 201., 201., 201.]], dtype=torch.float64)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors

In [44]:
cuda_is_available = torch.cuda.is_available()

In [51]:
if cuda_is_available:
    
    # Get a CUDA device object.
    my_cuda_device = torch.device("cuda")
    display(type(my_cuda_device), my_cuda_device, "-----")
    
    # Create a tensor in the default way.
    x = torch.ones(10, 20)
    display(type(x), x, "-----")
    
    # Directly create a tensor on GPU.
    y = torch.ones_like(x, device=my_cuda_device) + 3
    display(type(y), y, "-----")
    
    # Try adding without first making sure both tensors on same device:
    try:
        z = x + y
    except Exception as ex:
        print("Error\n", ex, "\n-----")
    
    # Transfer x to cuda.
    x = x.to(my_cuda_device)  # # or just use strings `.to("cuda")`
    z = x + y
    display(z, "-----")
    
    # Transfer back to CPU.
    z = z.to("cpu",  torch.double)  # Note: `.to` can also change dtype at the same time, as here.
    display(z, "-----")

torch.device

device(type='cuda')

'-----'

torch.Tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])

'-----'

torch.Tensor

tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4.]], device='c

'-----'

Error
 expected device cpu and dtype Float but got device cuda:0 and dtype Float 
-----


tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.]], device='c

'-----'

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
         5., 5.]], dtype=tor

'-----'