# Linear Models

From this guide: https://scikit-learn.org/stable/modules/linear_model.html

#### Note:
* Refer to vector $\mathbf{w}$ as `coef_` and $w_0$ (aka $b$) as `intercept_`

### [Ordinary Least Squares](https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares)

In [1]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])

LinearRegression()

In [2]:
reg.coef_

array([0.5, 0.5])

In [3]:
reg.intercept_

2.220446049250313e-16

In [4]:
reg.predict([[1.5, 1.5]])

array([1.5])

#### ⚠️ Warning: **multicollinearity**

The coefficient estimates for Ordinary Least Squares rely on the independence of the features. When features are correlated and the columns of the design matrix
have an **approximate linear dependence**, the design matrix becomes close to **singula**r and as a result, the least-squares estimate becomes highly sensitive to random errors in the observed target, producing a large variance. This situation of **multicollinearity** can arise, for example, when data are collected without an experimental design.

### [Ridge regression and classification](https://scikit-learn.org/stable/modules/linear_model.html#ridge-regression-and-classification)

In [5]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.5)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

Ridge(alpha=0.5)

In [6]:
reg.coef_

array([0.34545455, 0.34545455])

In [7]:
reg.intercept_

0.1363636363636364

In [8]:
reg.predict([[1.5, 1.5]])

array([1.17272727])

---

### A look at `RidgeClassifier`

> The Ridge regressor has a classifier variant: `RidgeClassifier`. This classifier first converts binary targets to `{-1, 1}` and then treats the problem as a regression task, optimizing the same objective as above. The predicted class corresponds to the sign of the regressor’s prediction. For multiclass classification, the problem is treated as multi-output regression, and the predicted class corresponds to the output with the highest value.

In [9]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import train_test_split
from IPython.display import display

In [10]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=101)
print(X_train.shape)
print(X_train[0])
print(y_test.shape)
print(y_test[0])

(426, 30)
[1.317e+01 1.822e+01 8.428e+01 5.373e+02 7.466e-02 5.994e-02 4.859e-02
 2.870e-02 1.454e-01 5.549e-02 2.023e-01 6.850e-01 1.236e+00 1.689e+01
 5.969e-03 1.493e-02 1.564e-02 8.463e-03 1.093e-02 1.672e-03 1.490e+01
 2.389e+01 9.510e+01 6.876e+02 1.282e-01 1.965e-01 1.876e-01 1.045e-01
 2.235e-01 6.925e-02]
(143,)
1


In [11]:
clf = RidgeClassifier().fit(X_train, y_train)

In [12]:
clf.get_params()

{'alpha': 1.0,
 'class_weight': None,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': False,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

In [13]:
print(clf.coef_.shape)
display(clf.coef_)
print(clf.intercept_)
display(clf.intercept_)

(1, 30)


array([[ 3.17715622e-01,  3.91183399e-03, -5.98678406e-03,
        -1.94898947e-03, -2.35923818e-01,  8.31182162e-02,
        -3.36432631e-01, -4.89128320e-01, -4.01751257e-01,
        -2.47037117e-03, -5.80264936e-01, -2.67387091e-02,
         1.83323341e-02, -3.33142059e-04, -6.91611380e-02,
         2.09853873e-01,  5.38900668e-01, -3.25060544e-02,
        -5.33803282e-02,  2.00747251e-02, -5.75684261e-01,
        -2.46569761e-02,  1.53541482e-02,  2.79396044e-03,
        -6.04025660e-01, -2.35153428e-01, -6.30611100e-01,
        -8.45232302e-01, -7.16762302e-01, -1.39276037e-01]])

[4.37355073]


array([4.37355073])

In [14]:
clf.classes_

array([0, 1])

* `predict()`:

In [15]:
clf.predict(X_test[0:5])

array([1, 1, 1, 0, 1])

* `score()`:

In [16]:
clf.score(X_test[0:5], y_test[0:5])

1.0

* `decision_function()`:

    In this case:
    > Predict confidence scores for samples. The confidence score for a sample is proportional to the signed distance of that sample to the hyperplane.

In [17]:
clf.decision_function(X_test[0:5])

array([ 0.78994738,  0.5125506 ,  0.85589808, -0.45582771,  1.19121259])

---

### [Setting the regularization parameter: leave-one-out Cross-Validation](https://scikit-learn.org/stable/modules/linear_model.html#setting-the-regularization-parameter-leave-one-out-cross-validation)

`RidgeCV`: The object works in the same way as `GridSearchCV` except that it defaults to **Leave-One-Out** Cross-Validation. Specifying the value of the `cv` attribute will trigger the use of cross-validation with `GridSearchCV`, for example `cv=10` for 10-fold cross-validation, rather than Leave-One-Out Cross-Validation.

In [18]:
import numpy as np
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])
reg.alpha_

0.01

### [Lasso](https://scikit-learn.org/stable/modules/linear_model.html#lasso)

* For an interesting example, see: [Compressive sensing: tomography reconstruction with L1 prior (Lasso)](https://scikit-learn.org/stable/auto_examples/applications/plot_tomography_l1_reconstruction.html#sphx-glr-auto-examples-applications-plot-tomography-l1-reconstruction-py)
* The `alpha` parameter controls the degree of sparsity of the estimated coefficients.

In [21]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)

In [23]:
X = [[0, 0], [1, 1]]
y = [0, 1]
print("X:", X)
print("y:", y)

X: [[0, 0], [1, 1]]
y: [0, 1]


In [24]:
reg.fit(X, y)

Lasso(alpha=0.1)

In [20]:
reg.predict([[1, 1]])

array([0.8])

### [Lasso: Hyperparameter Search Using cross-validation](https://scikit-learn.org/stable/modules/linear_model.html#using-cross-validation)

scikit-learn exposes objects that set the Lasso `alpha` parameter by **cross-validation**: 
* `LassoCV` and 
* `LassoLarsCV`. 

`LassoLarsCV` is based on the Least Angle Regression algorithm explained below.

For high-dimensional datasets with many collinear features, `LassoCV` is most often preferable. However, `LassoLarsCV` has the advantage of exploring more relevant values of `alpha` parameter, and if the number of samples is very small compared to the number of features, it is often faster than LassoCV.

Alternatively, the estimator 
* `LassoLarsIC` 

proposes to use the Akaike information criterion (AIC) and the Bayes Information criterion (BIC).

See this example for more details: [Lasso model selection: Cross-Validation / AIC / BIC](https://scikit-learn.org/stable/auto_examples/linear_model/plot_lasso_model_selection.html)

### [Multi-task Lasso](https://scikit-learn.org/stable/modules/linear_model.html#multi-task-lasso)

The `MultiTaskLasso` is a linear model that estimates sparse coefficients for multiple regression problems jointly: `y` is a **2D array**, of shape `(n_samples, n_tasks)`. The constraint is that the selected features are the same for all the regression problems, also called tasks.

### [Elastic-Net](https://scikit-learn.org/stable/modules/linear_model.html#elastic-net)

`ElasticNet` is a linear regression model trained with both $l_1$ and $l_2$-norm regularization of the coefficients.

This combination allows for learning a sparse model where few of the weights are non-zero like `Lasso`, while still maintaining the regularization properties of Ridge. We control the convex combination of $l_1$ and $l_2$ using the `l1_ratio` parameter.

### [Mutli-task Elastic-Net](https://scikit-learn.org/stable/modules/linear_model.html#multi-task-elastic-net)

The `MultiTaskElasticNet` is an elastic-net model that estimates sparse coefficients for multiple regression problems jointly: `Y` is a **2D array** of shape `(n_samples, n_tasks)`. The constraint is that the selected features are the same for all the regression problems, also called tasks.

### [Least Angle Regression (LARS)](https://scikit-learn.org/stable/modules/linear_model.html#least-angle-regression)

Least-angle regression (LARS) is a regression algorithm for high-dimensional data. LARS is similar to forward stepwise regression. At each step, it finds the feature most correlated with the target. 

### [LARS Lasso](https://scikit-learn.org/stable/modules/linear_model.html#lars-lasso)

`LassoLars` is a lasso model implemented using the LARS algorithm, and unlike the implementation based on coordinate descent, this yields the exact solution, which is piecewise linear as a function of the norm of its coefficients.

In [25]:
from sklearn import linear_model
reg = linear_model.LassoLars(alpha=.1)
reg.fit([[0, 0], [1, 1]], [0, 1])
reg.coef_

array([0.71715729, 0.        ])

### [Orthogonal Matching Pursuit (OMP)](https://scikit-learn.org/stable/modules/linear_model.html#orthogonal-matching-pursuit-omp)

`OrthogonalMatchingPursuit` and `orthogonal_mp` implements the OMP algorithm for approximating the fit of a linear model with constraints imposed on the number of non-zero coefficients $l_0$ (i.e. the pseudo-norm).

### [Bayesian Regression](https://scikit-learn.org/stable/modules/linear_model.html#bayesian-regression)

> Bayesian regression techniques can be used to include regularization parameters in the estimation procedure: the regularization parameter is not set in a hard sense but tuned to the data at hand.

> 📚 This is well explained in: *C. Bishop: Pattern Recognition and Machine learning*

* [Bayesian Ridge Regression](https://scikit-learn.org/stable/modules/linear_model.html#bayesian-ridge-regression): `BayesianRidge`
* [Automatic Relevance Determination - ARD](https://scikit-learn.org/stable/modules/linear_model.html#automatic-relevance-determination-ard): `ARDRegression`

In [29]:
# BayesianRidge example:
from sklearn import linear_model

X = [[0., 0.], [1., 1.], [2., 2.], [3., 3.]]
Y = [0., 1., 2., 3.]
print("X:", X)
print("y:", Y)

reg = linear_model.BayesianRidge()

reg.fit(X, Y)
print("w:", reg.coef_)

print("predicion for [1., 0.]:")
print(reg.predict([[1, 0.]]))

X: [[0.0, 0.0], [1.0, 1.0], [2.0, 2.0], [3.0, 3.0]]
y: [0.0, 1.0, 2.0, 3.0]
w: [0.49999993 0.49999993]
predicion for [1., 0.]:
[0.50000013]


### [Logistic regression](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression)

Logistic regression, despite its name, is a linear model for classification rather than regression. Logistic regression is also known in the literature as logit regression, maximum-entropy classification (MaxEnt) or the log-linear classifier. In this model, the probabilities describing the possible outcomes of a single trial are modeled using a logistic function.

Logistic regression is implemented in `LogisticRegression`. This implementation can fit **binary**, **One-vs-Rest**, or **multinomial** logistic regression with optional $l_1$, $l_2$, or Elastic-Net regularization.

### [Generalized Linear Regression](https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-regression)

* See therory at the above link.
* Implementation provided is `TweedieRegressor`.

### [Stochastic Gradient Descent - SGD](https://scikit-learn.org/stable/modules/linear_model.html#stochastic-gradient-descent-sgd)

Stochastic gradient descent is a simple yet very efficient approach to fit linear models. It is particularly useful when the number of samples (and the number of features) is very large. The `partial_fit` method allows online/out-of-core learning.

Provided are:
* SGDClassifier 
* SGDRegressor

These fit linear models for classification and regression using different (convex) loss functions and different penalties. E.g., with `loss="log"`, `SGDClassifier` fits a logistic regression model, while with `loss="hinge"` it fits a linear support vector machine (SVM).

### [Perceptron](https://scikit-learn.org/stable/modules/linear_model.html#perceptron)

* `Perceptron` is a classification algorithm which shares the same underlying implementation with `SGDClassifier`. In fact, `Perceptron()` is equivalent to `SGDClassifier(loss="perceptron", eta0=1, learning_rate="constant", penalty=None)`

### [Passive Aggressive Algorithms](https://scikit-learn.org/stable/modules/linear_model.html#passive-aggressive-algorithms)

The passive-aggressive algorithms are a family of algorithms for large-scale learning. They are similar to the Perceptron in that they do not require a learning rate. However, contrary to the Perceptron, they include a regularization parameter `C`.

For classification, `PassiveAggressiveClassifier` can be used with `loss='hinge'` (PA-I) or `loss='squared_hinge'` (PA-II). For regression, `PassiveAggressiveRegressor` can be used with `loss='epsilon_insensitive'` (PA-I) or `loss='squared_epsilon_insensitive'` (PA-II).

### [Robustness regression: outliers and modeling errors](https://scikit-learn.org/stable/modules/linear_model.html#robustness-regression-outliers-and-modeling-errors)

See theory at the above link.

Provided are:
* `RANSACRegressor`
* `TheilSenRegressor`
* `HuberRegressor`

### [Polynomial regression: extending linear models with basis function](https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions)

One common pattern within machine learning is to use linear models trained on nonlinear functions of the data. This approach maintains the generally fast performance of linear methods, while allowing them to fit a much wider range of data.

For example, a simple linear regression can be extended by constructing **polynomial features** from the coefficients. 

Polynomial regression is in the same class of linear models we considered above (i.e. the model is linear in $w$) and can be solved by the same techniques. By considering linear fits within a higher-dimensional space built with these basis functions, the model has the flexibility to fit a much broader range of data.

* The provided **transformer** is `PolynomialFeatures`

In [30]:
# Example of using PolynomialFeatures:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(6).reshape(3, 2)
print(X)

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
print(X_poly)

[[0 1]
 [2 3]
 [4 5]]
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


The features of `X` have been transformed from $[x_1, x_2]$ to $[1, x_1, x_2, x^2_1, x_1 x_2, x^2_2]$, and can now be used within any linear model.

This sort of preprocessing can be streamlined with the `Pipeline` tools. A single object representing a simple polynomial regression can be created and used as follows:

In [34]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

pipe = Pipeline(
    [
        ('poly', PolynomialFeatures(degree=3)),  # <-- Transform here.
        ('linear', LinearRegression(fit_intercept=False))
    ]
)

In [35]:
# fit to an order-3 polynomial data
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
print("x:", x)
print("y:", y)

x: [0 1 2 3 4]
y: [  3   1  -5 -21 -53]


In [36]:
pipe = pipe.fit(x[:, np.newaxis], y)
pipe.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])

The linear model trained on polynomial features is able to exactly recover the input polynomial coefficients (by nature of this example).

In some cases it’s not necessary to include higher powers of any single feature, but only the so-called *interaction features* that multiply together at most $d$ distinct features. These can be gotten from `PolynomialFeatures` with the setting `interaction_only=True`.

For example, when dealing with boolean features, $x^n_i=x_i$ for all $n$ and is therefore useless; but $x_i x_j$ represents the conjunction of two booleans. This way, we can solve the XOR problem with a linear classifier:

In [41]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] ^ X[:, 1]
print("X:\n", X)
print("y = X[:, 0] ^ X[:, 1]:", y)

X:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
y = X[:, 0] ^ X[:, 1]: [0 1 1 0]


In [42]:
X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)
print("X after `PolynomialFeatures` applied (interaction_only=True):", X)

X after `PolynomialFeatures` applied (interaction_only=True): [[1 0 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [1 1 1 1]]


In [44]:
# Now fit a Perceptron (which by itself can't solve XOR)
clf = Perceptron(
    fit_intercept=False, 
    max_iter=10, 
    tol=None,
    shuffle=False
).fit(X, y)

In [45]:
clf.predict(X)

array([0, 1, 1, 0])

In [46]:
clf.score(X, y)

1.0

And the classifier “predictions” are perfect.